[project]
name = "template_mlops_e2e"
version = "0.1.0"
description = "Test UV, Pytest and Github Actions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.0",
    "pytest-cov>=7.0.0",
]